version: "3"

services:
  nginx:
    image: ghcr.io/cssnr/docker-nginx-proxy:latest
    environment:
      - SERVICE_NAME=shields
    ports:
      - "80:80"

  shields:
    image: ghcr.io/smashedr/shields:pr-validation
