version: "3.8"

services:
  nginx:
    build:
      context: nginx
    image: ghcr.io/cssnr/docker-nginx-proxy:latest
    environment:
      - SERVICE_NAME=shields
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 32M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.cssnr-shields-http.rule=Host(`shields.cssnr.com`)
        - traefik.http.routers.cssnr-shields-http.entrypoints=http
        - traefik.http.routers.cssnr-shields-http.middlewares=https-redirect
        - traefik.http.routers.cssnr-shields-https.rule=Host(`shields.cssnr.com`)
        - traefik.http.routers.cssnr-shields-https.entrypoints=https
        - traefik.http.routers.cssnr-shields-https.tls=true
        - traefik.http.services.cssnr-shields-https.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD-SHELL", "curl -sf localhost:80/health-check || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - shields
    networks:
      - internal
      - traefik-public

  shields:
    image: ghcr.io/smashedr/shields:pr-validation
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
